language: php

services:
  - mysql

php:
  - 5.6

env:
  - DB=mysql

before_script:
- sudo pip install PyMySQL
- sudo pip install -U robotframework-databaselibrary 
- sudo apt-get update && sudo apt-get install -y python python-pip # TODO: SEE BELOW ABOUT ROBOT TESTS#
- mysql -e 'CREATE DATABASE IF NOT EXISTS root;'
- sudo pip install -r robot/requirements.txt # TODO: SEE BELOW ABOUT ROBOT TESTS#
- mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'127.0.0.1';" -uroot

script: 
- phpunit --configuration phpunit_mysql.xml --coverage-text 
- cd src
- cp config/dbaccess.php.template config/dbaccess.php
- php -S localhost:8000 &> /dev/null &
- cd -
# TODO: write robot tests and uncomment pybot to run
- cd robot
- pybot db_test.robot


before_deploy:
  - openssl aes-256-cbc -K $encrypted_2390d7ff4426_key -iv $encrypted_2390d7ff4426_iv -in auth.enc -out auth -d
  - chmod 600 auth

deploy:
  - provider: script
    skip_cleanup: true
    script: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -tt -i auth ubuntu@auth.arcada.nitor.zone /home/ubuntu/update.sh
    on:
      branch: master
