language: php

services:
  - mysql

php:
  - 5.6

env:
  - DB=mysql

before_script:
# pip install requests[security]
- sudo apt-get update && sudo apt-get install -y python python-pip # TODO: SEE BELOW ABOUT ROBOT TESTS#
- mysql -e 'CREATE DATABASE IF NOT EXISTS auth;'
- sudo pip install -r robot/requirements.txt # TODO: SEE BELOW ABOUT ROBOT TESTS#

script: 
- phpunit --configuration phpunit_mysql.xml --coverage-text 
# TODO: write robot tests and uncomment theese to run
- cd src
- cp config/dbaccess.php.template config/dbaccess.php
- php -S localhost:8000 &> /dev/null &
- cd -
- pybot robot/


before_deploy:
  - openssl aes-256-cbc -K $encrypted_2390d7ff4426_key -iv $encrypted_2390d7ff4426_iv -in auth.enc -out auth -d
  - chmod 600 auth

deploy:
  - provider: script
    skip_cleanup: true
    script: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -tt -i auth ubuntu@auth.arcada.nitor.zone /home/ubuntu/update.sh
    on:
      branch: master
